package:
  name: my_versions
  version: "0.6"

source:
    path: ../

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
      - my_versions = my_versions.__main__:main

  osx_is_app: True


requirements:
  build:
    - python
    - setuptools
    - gdal
    - numpy
    - pandas
    - matplotlib

  run:
    - python
    - setuptools
    - gdal
    - numpy
    - pandas
    - matplotlib
    - python.app [osx]

app:
  entry: my_versions
  type: desk

