package:
  name: my_versions
  version: "1.0"


source:
    path: ../


build:
  number: 0

  entry_points:
      - my_versions = my_versions.__main__:main

  osx_is_app: True


requirements:
  build:
    - python >=3
    - setuptools

  run:
    - python >=3
    - gdal
    - numpy
    - pandas
    - matplotlib
    - python.app [osx]


app:
  entry: my_versions
  type: desk
